/* GENERATED by tools/build-web.js — do not edit; change production.config.json and build again.
   The anon key below is public by design. What protects the data is Row Level Security. */
window.IMODE_ENV=Object.freeze({
 "production": true,
 "version": "Version 1.0",
 "builtAt": "2026-10-10T06:41:45.049Z",
 "customerHost": "",
 "customerByUrl": true,
 "staffHost": "imodeservice.github.io",
 "cloud": {
  "url": "https://cwrkquzuuyhfhesozqnb.supabase.co",
  "key": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cmtxdXp1dXloZmhlc296cW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1NTgwNzAsImV4cCI6MjEwNjEzNDA3MH0.JhWDk3su9Pf9XZSPTDe4sWJiHKE3Pl2OPKHvTj0QTgw"
 },
 "line": {
  "addFriendUrl": "https://line.me/R/ti/p/%40imodeservice",
  "officialAccountId": "@imodeservice"
 }
});
